# ##################################
# Security - Everybody Out 1min
# ##################################
  - alias: security_everybody_out_1min
    id: security_everybody_out_1min
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.family_home
        to: 'off'
        for:
          minutes: 1
    # condition:
    #   - condition: state
    #     entity_id: switch.guestmode
    #     state: 'off'
    action:
      - service: notify.mobile_app_denis_phone
        data:
          message: Включение режима охраны через 1 минуту!
          title: Никого нет дома!
          data:
            actions: 
              - action: guestmode
                title: Гостевой режим
                authenticationRequired: false
                activationMode: background
                icon: "sfsymbols:person.circle.fill"


# ##################################
# Security - Everybody Out 1min - Mobile App Reply
# ##################################
  - alias: security_everybody_out_reply_from_app
    id: security_everybody_out_reply_from_app
    initial_state: true
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "guestmode"
    action:
      - service: switch.turn_on
        entity_id: input_boolean.system_guest_mode

# ##################################
# Security - Wrapper
# ##################################
  - alias: security_wrapper
    id: security_wrapper
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.family_home
        to: 'off'
        for:
          minutes: 2
        id: 'to_on'
      - platform: state
        entity_id: binary_sensor.family_home
        to: 'on'
        for:
          seconds: 15
        id: 'to_off'
    condition:
      - condition: state
        entity_id: input_boolean.system_guest_mode
        state: 'off'
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: 'to_on'
            sequence:
              - service: switch.turn_on
                entity_id: input_boolean.system_security_mode
          - conditions:
              - condition: trigger
                id: 'to_off'
            sequence:
              - service: switch.turn_off
                entity_id: input_boolean.system_security_mode, input_boolean.system_guest_mode
      - delay:
          seconds: 3
      - service: notify.telegram
        data:
          message: "\U0001f46e Режим охраны {{ iif(is_state('input_boolean.system_security_mode','off'), 'выключен!', 'включен!', '')}}"

# ##################################
# Security - Turn  On
# ##################################
  - alias: security_state_change
    id: security_state_change
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.system_security_mode
        to:
        for:
          seconds: 15
    action:
      - choose:
          - conditions:
              - condition: state 
                entity_id: input_boolean.system_security_mode
                state: 'on'
            sequence:
              - service: notify.telegram
                data:
                  message: "\U0001F3e2 Никого нет дома, выключаем освещение!"
              - service: script.turn_on
                entity_id: script.away_mode_on
              - service: notify.telegram
                data:
                  message: "\U0001f514 Освещение выключено!"
          - conditions:
              - condition: state 
                entity_id: input_boolean.system_security_mode
                state: 'off'
            sequence:
              - service: input_boolean.turn_off
                data:
                  entity_id: input_boolean.system_security_mode
              - service: script.turn_on
                entity_id: script.away_mode_off

# ##################################
# Security - Sensors State change
# ##################################
  - alias: security_sensors_state_change
    id: security_sensors_state_change
    initial_state: true
    mode: queued
    max: 25
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.hall_d_contact
          - binary_sensor.kitchen_d_contact
          - binary_sensor.kidroom_big_d_contact
          - binary_sensor.kidroom_small_d_contact
          - binary_sensor.bedroom_d_contact
        to:
      - platform: state
        entity_id:
          - binary_sensor.hall_m_occupancy
          - binary_sensor.bathroom_m_occupancy
          - binary_sensor.livingroom_m_occupancy
          - binary_sensor.kitchen_m_occupancy
          - binary_sensor.bedroom_m_occupancy
          - binary_sensor.kidroom_m_occupancy
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.system_security_mode
        state: "on"
      - condition: state
        entity_id: timer.security_delay
        state: "idle"
      - condition: numeric_state
        entity_id: sensor.uptime_custom
        above: 0
    action:
      - service: notify.telegram
        data:
          message: "\U0001f46e Сработал датчик {{trigger.to_state.attributes.friendly_name}}!"
  
# # ##################################
# # Security - Alarm delay
# # ##################################
#   - alias: security_alarm_delay
#     id: security_alarm_delay
#     initial_state: true
#     mode: single
#     max_exceeded: silent
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.0x00158d0001e5d6be_contact
#         from: "off"
#         to: "on"
#     condition:
#       - condition: state
#         entity_id: input_boolean.system_security_mode
#         state: "on"
#     action:
#       - service: timer.cancel
#         entity_id: timer.security_delay
#       - service: timer.start
#         entity_id: timer.security_delay

#   # # ##################################
#   # # Security - Security system PWR status
#   # # ##################################
#   # - alias: security_system_pwr
#   #   initial_state: true
#   #   trigger:
#   #     - platform: state
#   #       entity_id: binary_sensor.d1_security_power
#   #   action:
#   #     - service: notify.telegram
#   #       data:
#   #         message: "\U0001f693 Охранная система: питание {% if is_state('binary_sensor.d1_security_power','on') %}включено!{% else %}выключено!{% endif %}"
  
#   # # ##################################
#   # # Security - Security system armed
#   # # ##################################
#   # - alias: security_system_armed
#   #   initial_state: true
#   #   trigger:
#   #     - platform: state
#   #       entity_id: binary_sensor.d1_security_armed
#   #   action:
#   #     - service: notify.telegram
#   #       data:
#   #         message: "\U0001f693 Охранная система {% if is_state('binary_sensor.d1_security_armed','on') %}включена!{% else %}выключена!{% endif %}"
  
#   # # ##################################
#   # # Security - Security system alarm
#   # # ##################################
#   # - alias: security_system_alarm
#   #   initial_state: true
#   #   trigger:
#   #     - platform: state
#   #       entity_id: binary_sensor.d1_security_alarm
#   #   action:
#   #     - service: notify.telegram
#   #       data:
#   #         message: "\U0001f693 Охранная система: Тревога {% if is_state('binary_sensor.d1_security_alarm','on') %}включена!{% else %}выключена!{% endif %}"
  
# # ##################################
# # Security- Main door vibration
# # ##################################
#   - alias: security_main_door_vibration
#     id: security_main_door_vibration
#     initial_state: true
#     trigger:
#       - platform: state
#         entity_id: sensor.0x00158d0002b5fbc1_action
#         to: "vibration"
#     condition:
#       - condition: state
#         entity_id: input_boolean.system_security_mode
#         state: "on"
#     action:
#       - service: notify.telegram
#         data:
#           message: "\U0001F6AA Внимание! Главная дверь - Вибрация!"
  
# # ##################################
# # Security - Sensors State change over night
# # ##################################
  - alias: security_sensors_state_change_night
    id: security_sensors_state_change_night
    initial_state: true
    mode: queued
    max: 25
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.hall_d_contact
          - binary_sensor.kitchen_d_contact
          - binary_sensor.kidroom_big_d_contact
          - binary_sensor.kidroom_small_d_contact
          - binary_sensor.bedroom_d_contact
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.tod_day
        state: "off"
      - condition: state
        entity_id: input_boolean.system_security_mode
        state: "off"
    action:
      - service: notify.telegram
        data:
          message: >-
            {{"\U0001f46e"}}
            {%-if trigger.to_state.attributes.device_class=='window' and trigger.to_state.state=='on'%}Открыто {{trigger.to_state.attributes.friendly_name}}
            {%-elif trigger.to_state.attributes.device_class=='window' and trigger.to_state.state=='off'%}Закрыто {{trigger.to_state.attributes.friendly_name}}
            {%-elif trigger.to_state.attributes.device_class=='door' and trigger.to_state.state=='on'%}Открыта {{trigger.to_state.attributes.friendly_name}}
            {%-elif trigger.to_state.attributes.device_class=='door' and trigger.to_state.state=='off'%}Закрыта {{trigger.to_state.attributes.friendly_name}}
            {%-else%}NA{%endif%}